import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Award,
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Car,
  CheckCircle2,
  Circle,
  Clock,
  CreditCard,
  Dumbbell,
  FileText,
  Flame,
  Flag,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Layers,
  ListTodo,
  MoreHorizontal,
  Package,
  PiggyBank,
  Receipt,
  Repeat,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  UserRound,
  Users,
  Utensils,
  Wallet,
} from "lucide-react";

/**
 * Icon registry.
 *
 * Records store an icon *name* rather than an imported component, because the
 * value comes from the database and a component cannot be serialised. The
 * registry is the only place the mapping exists, and an unknown name falls
 * back to a neutral glyph instead of rendering nothing.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  award: Award,
  banknote: Banknote,
  "book-open": BookOpen,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  car: Car,
  "check-circle": CheckCircle2,
  circle: Circle,
  clock: Clock,
  "credit-card": CreditCard,
  dumbbell: Dumbbell,
  "file-text": FileText,
  flame: Flame,
  flag: Flag,
  "gamepad-2": Gamepad2,
  gift: Gift,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  home: Home,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  "list-todo": ListTodo,
  "more-horizontal": MoreHorizontal,
  package: Package,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  repeat: Repeat,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  sparkles: Sparkles,
  target: Target,
  "trending-up": TrendingUp,
  user: UserRound,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
};

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (!name) return Circle;
  return ICON_MAP[name] ?? Circle;
}

/** Names offered in pickers, grouped so a long list stays navigable. */
export const ICON_OPTIONS: Array<{ name: string; label: string }> = [
  { name: "target", label: "Target" },
  { name: "flag", label: "Bendera" },
  { name: "layers", label: "Lapisan" },
  { name: "list-todo", label: "Daftar tugas" },
  { name: "check-circle", label: "Selesai" },
  { name: "clock", label: "Waktu" },
  { name: "calendar", label: "Kalender" },
  { name: "flame", label: "Semangat" },
  { name: "sparkles", label: "Spesial" },
  { name: "activity", label: "Aktivitas" },
  { name: "dumbbell", label: "Olahraga" },
  { name: "heart-pulse", label: "Kesehatan" },
  { name: "book-open", label: "Belajar" },
  { name: "graduation-cap", label: "Pendidikan" },
  { name: "briefcase", label: "Karier" },
  { name: "laptop", label: "Kerja" },
  { name: "wallet", label: "Dompet" },
  { name: "banknote", label: "Uang tunai" },
  { name: "landmark", label: "Bank" },
  { name: "smartphone", label: "E-wallet" },
  { name: "piggy-bank", label: "Tabungan" },
  { name: "credit-card", label: "Kartu" },
  { name: "receipt", label: "Tagihan" },
  { name: "cart", label: "Belanja" },
  { name: "shopping-bag", label: "Belanja" },
  { name: "utensils", label: "Makanan" },
  { name: "car", label: "Transportasi" },
  { name: "home", label: "Rumah" },
  { name: "gamepad-2", label: "Hiburan" },
  { name: "repeat", label: "Berulang" },
  { name: "trending-up", label: "Pertumbuhan" },
  { name: "user", label: "Pribadi" },
  { name: "users", label: "Sosial" },
  { name: "gift", label: "Hadiah" },
  { name: "award", label: "Pencapaian" },
  { name: "package", label: "Barang" },
  { name: "file-text", label: "Catatan" },
];
